### ISSUE TITLE
Column Reorder

### ISSUE THREAD

**Issue by rgeerts** [mike-allison/KODataTable#1]
Really liked your interface.  So used your code in a project and implemented a column reordering functionality with the help of an existing column reordering tool. [here](https://github.com/rgeerts/KODataTable-dragable). thanks

**Comment by mikeallisonJS** [comment]
Awesome! I tried your jsfiddle, but it doesn't seem to be working. I'd love
to see this, and I'll happily add a link to it once I see it up and running.

**Comment by rgeerts** [comment]
grrr!  You weren't logged into the same site as me.  I'll forgo giving you my creds and I tried something different and posted it

**Comment by mikeallisonJS** [comment]
Awesome, I added a link on the main page. I'll add one to github once I get
the time to do a proper readme there.

Thanks again!
