### ISSUE TITLE
Getting error changing pages

### ISSUE THREAD

**Issue by rdmdev** [mike-allison/KODataTable#2]
Congrats this work, it's pretty cool.

When implementing this plugin I've came across with an odd behaviour while switching pages - although I was unable to reproduce it on the examples page.
Here's my case (using Chrome  Version 43.0.2357.65 m - developer tools on):
- Initial page rendered 20 items;
- 1st click on the **Next** rendered one item;
- 2nd and following clicks on the **Next** rendered zero items;
- Clicking in **Last** rendered the last 20 items.

Solved it by changing from

``` javascript
 this.currentRows = ko.computed((function(_this) {
        return function() {
          if ((_this.currentPage() + 1) * _this.pageSize() > _this.filteredRows().length) {
            return _this.filteredRows().slice(_this.currentPage() * _this.pageSize());
          } else {
            return _this.filteredRows().slice(_this.currentPage() * _this.pageSize(), 
+((_this.currentPage() + 1 * _this.pageSize()) - 1) + 1 || 9e9);
          }
        };
```

to

``` javascript
 this.currentRows = ko.computed((function(_this) {
        return function() {
          if ((_this.currentPage() + 1) * _this.pageSize() > _this.filteredRows().length) {
            return _this.filteredRows().slice(_this.currentPage() * _this.pageSize());
          } else {
            return _this.filteredRows().slice(_this.currentPage() * _this.pageSize(),
 +(((_this.currentPage() + 1) * _this.pageSize()) - 1) + 1 || 9e9);
          }
        };
```

Case it's not clear, wrapped the __this.currentPage() + 1_  with an extra **()** in the **else** block... You have it in the **if** statement.
Like I wrote, in your example page it works fine.
I'm using bower in this implementation.
Hope it helps.

**Comment by mikeallisonJS** [comment]
Thanks, I just got this fix pushed out :)
